spring:
  datasource:
    username: root
    password: heroxin
    url: jdbc:mysql://192.168.196.101:3306/gulimall_ums
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    将服务注册到Nacos，需要nacos地址和服务名称
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848

  application:
    name: GuliMall-Member
#    配置mybatis-plus，需要扫描mapper文件，设置主键自增
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 8000