#    将服务注册到Nacos，需要nacos地址和服务名称
spring:
  application:
    name: GuliMall-GateWay
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: test_route
          uri: https://heroxin.xyz
          predicates:
            - Query=url,heroxin
            #              将所有前端请求路由到 renren-fast
#
        - id: product_rout
          uri: lb://GuliMall-Product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}


server:
  port: 88


