server:
  port: 20000
  servlet:
    session:
#      session 过期时间
      timeout: 30m
spring:
  application:
    name: GuliMall-Auth
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
  redis:
    host: 192.168.196.101
    port: 6379
#    spring session
  session:
    store-type: redis
